### ISSUE TITLE
CodeSandbox crash errors

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#1136]
https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

**Comment by dcwarwick** [comment]
I see this on multiple codesandboxes:
![image](https://user-images.githubusercontent.com/6385315/129062579-13130200-2985-4283-bb83-8873f72897ff.png)

**Comment by lee-chase** [comment]
Seen on ExampleComponent, rectified by removing ~ from the start of CSS import https://codesandbox.io/s/examplecomponent-8189x?file=/src/_ibm-cloud-and-cognitive.scss

![image](https://user-images.githubusercontent.com/15086604/129070359-c66de39d-6366-484e-9ddf-31160abc86bf.png)

**Comment by dcwarwick** [comment]
OK, the errors in Simon's original example (https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox) seem to be simply that there are missing dependencies from `package.json` in our example projects -- they run locally because of the global monorepo node_modules folder having lots of goodies in it. Running `yarn clean` in the monorepo then changing down to an example folder and trying to build/run it should reproduce this error locally.

This is probably unrelated to the issues we've had with codesandbox generally being buggered recently.

**Comment by dcwarwick** [comment]
I'm now seeing the "Path must be a string. Received null" message from codesandboxes that were previously giving me the "NoSuchMethodError" message.

**Comment by dcwarwick** [comment]
Looks like removing the ~ from these paths fixes it:
![image](https://user-images.githubusercontent.com/6385315/129075777-73b64197-fa70-4cbd-b6c8-51bda46fc649.png)
