### ISSUE TITLE
CreateFullPage: Release Review

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#1163]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to main.
- [x] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [x] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [x] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.
- [x] Each public component SCSS lists all of the Carbon and C&CS components imported and used by the JavaScript code and explicitly imports the SCSS for each of these components.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [x] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by sydrosa** [comment]
Design Review: 

[Issue 1121](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/1121)
[Review](https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1114)

**Comment by sydrosa** [comment]
[Code sandbox](https://codesandbox.io/s/createfullpage-example-nj798)

**Comment by davidmenendez** [comment]
everything looks good to me. there's a lot to take in though, so i'd definitely recommend getting at least one other person to take a look. the only glaring thing is that `constants` and `CreateFullPageSection` need the copyright added. good job!

**Comment by elycheea** [comment]
Since this is moving out of Canary, there shouldn’t be any breaking changes?

- The design guidance in Carbon patterns does include an optional toggle for the Create full page details. I believe this was also in an earlier version as a scenario — is this still an anticipated scenario?
- Not seeing `includeViewAllToggle` in the Controls but I do see it listed as a prop. There doesn’t seem to be much of a convention here yet but the closest comparisons I can find from Carbon are `withOverlay` in Loading and `hasMargin` in FormGroup.
- For accessibility, should there be a way to tab through the sidenav? Although never mind — doesn’t look like the individual sections are clickable either.
  - When simulating an error with g90 or g100 themes, we do run into some contrast issues — but looks like that’s just a part of the story and shouldn’t be an issue in actual implementation.

     > ![image](https://user-images.githubusercontent.com/1717398/130680016-4e311190-b6ba-49ad-9691-1bf969977c05.png)
  - 👍 that hidden steps/sections are actually hidden from keyboard/screen reader using display: hidden

### Testing
- I’m seeing the test case `should click the back button and add a custom next button label on a single step` twice.
- Do we need to test for accessibility violations?
- Do we need separate tests for `CreateFullPageSection` and `CreateFullPageStep`?

### Documentation
- Not sure why, but the CreateFullPageStep in Docs is showing a bunch of `unknown`s even though I see these defined.

    > ![image](https://user-images.githubusercontent.com/1717398/130697077-52994078-541c-45ba-9613-7c125c337401.png)
- Does CodeSandbox also need to demonstrate the various design scenarios (w/ and w/o sections?)
  - Pretty minor, but did notice the modal buttons aren’t edge-to-edge in CodeSandbox like they are in Storybook.

      > ![image](https://user-images.githubusercontent.com/1717398/130697768-c5d83731-3f12-4a8e-867a-9be65b23fa4a.png)

One last thing, I did see a comment that mentioned that the view all toggle isn’t supported yet. I don’t think that’s super clear from the documentation since we still include `includeViewAllToggle` and other `viewAllToggle` props. If I’m misunderstanding, might be helpful to clarify further!

```
// currently, we are not supporting the use of 'view all' toggle state or CreateFullPageSection -- this may be a future feature
```

**Comment by matthewgallo** [comment]
Component has been released! 🎉
