### ISSUE TITLE
APIKeyModal: breaking behavior in code sandbox

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1257]
## What package(s) are you using?

- [X] Cloud & Cognitive

## Detailed description

> Describe in detail the issue you're having.

For some reason, the `Copy` button inside of the APIKeyModal makes the component break (this has only been observed within code sandbox.
> Is this issue related to a specific component?

APIKeyModal
> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the api key to be copied to my clipboard
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-cloud-cognitive packge are you using?

Latest

## Steps to reproduce the issue

1. Click generate button in the APIKeyModal code sandbox
2. Then when the modal opens, click the `Copy` button
3. At this point, you should see the breaking behavior.

> Please create a reduced test case in CodeSandbox
>

https://codesandbox.io/s/apikeymodal-lln03

https://user-images.githubusercontent.com/10215203/133331065-20d79a9c-ec86-4c5d-9680-4ba80aec882a.mov

**Comment by davidmenendez** [comment]
<img width="1100" alt="Screen Shot 2021-09-15 at 10 32 53 AM" src="https://user-images.githubusercontent.com/6370760/133463815-717f34b1-e1de-4e1f-b13f-a9188a86dd67.png">

the fixes appear to be working. it's weird though because this only seems to be a problem on chrome in sandbox and not firefox. either way the error appears to be fixes.
