### ISSUE TITLE
PageHeader component z-index conflicts with security--toolbar__panel menu z-index.

### ISSUE THREAD

**Issue by Nishi-Chandra1** [carbon-design-system/ibm-cloud-cognitive#1302]
1.  z-index for .exp--page-header.exp--page-header  class is set to 8000 which is equal to the z-index of .bx--header but its getting conflict by z-index of  security--toolbar__panel
<img width="1792" alt="Screenshot 2021-09-30 at 9 08 17 PM" src="https://user-images.githubusercontent.com/80027651/135486872-75bc94a7-7b2c-44bf-ae02-96206c7b8994.png">
.

I have fixed it in local it by setting z-index of  .exp--page-header.exp--page-header to 7999, z-index of .bx--header to 8000( z-index of security--toolbar__panel is 8001).

**Comment by dcwarwick** [comment]
@Nishi-Chandra1 Can you explain a bit more what exactly the problem is, and why you think it's a bug in the PageHeader?

We set the z-index of the PageHeader in order to prevent problems in which content was rising above the header while scrolling. Carbon defines a standard z-index for headers, which is 8000, and we are using that value just as Carbon headers (eg in UIShell) do. You say that this is conflicting with the z-index of security--toolbar__panel, but you then say that the z-index of security--toolbar__panel is 8001, so I don't see how that makes a conflict, and besides that is presumably one of your own classes so you could change that value if necessary.

What exactly is the conflict are you getting, and what undesirable effect does it produce? Thank you for including a screenshot, but I'm not sure what to look for in it -- can you explain what is wrong or unexpected there? Thanks!

**Comment by Nishi-Chandra1** [comment]
I am not sure what exactly is conflicting here. But when i am setting z-index of main header and pageHeader to 8000 in that case toolbar panel with z-index 8001 is getting hidden back side of pageheader as you can see in the screenshot. you can check it by using all the 3 components together. For more reference i have already shown the demo to @lee-chase  , may be he can explain in more detail here.

**Comment by lee-chase** [comment]
So the sidenav (part of the header) goes under the page header. 

https://codesandbox.io/s/pageheaderexample-forked-tf7oy?file=/src/components/CommonHeader/CommonHeader.js

Reducing the page header by 1 seems like a reasonable course of action
