### ISSUE TITLE
WebTerminal: release review

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1415]
## What will this achieve?

A release review needs to happen in order for us to release the `WebTerminal` component.

The release review guidelines can be found [here](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/docs/reviews/RELEASE_REVIEW_GUIDELINES.md)

### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to main.
- [x] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [ ] Public component supports a Devtools attribute 
- [x] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.
- [x] Each public component SCSS lists all of the Carbon and C&CS components imported and used by the JavaScript code and explicitly imports the SCSS for each of these components.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [x] All components utilizing motion must include reduced-motion queries for accessibility purposes - read more here.
- [x] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by elycheea** [comment]
@AlexanderMelox here are initial comments from review with @qbi11y and @glapadre today.

### Readiness 
- Design review completed by Laura Marshall #1958.

### Engineering review
- The terminal itself does not include a way to interact or type on it. Wanted to check that this is intentional or if it’s something for the consumer to implement?
- Can we change `closeTerminal` to `onClose` or `onCloseTerminal` instead for consistency.
- Any reason we need to be so descriptive as to call it `documentationLinks` instead of just `links`? If we end up simplifying this, then `documentationLinksIconDescription` should also follow suit.
- In terms of responsiveness, when the screen reaches below `640px`, the web terminal should probably have a max-width of 100%.
- It looks like there’s one accessibility violation on the overflow menu where the documentation links are.
   > ![image](https://user-images.githubusercontent.com/1717398/178348212-0e8cdca3-3a42-4c66-9623-d1045bf236c8.png)

  But I think you can resolve this by adding `ariaLabel={documentationLinksIconDescription}` to the OverflowMenu so that the icon description matches the actual aria label.
- WebTerminal line 104-105 `className` and `blockClass` should be flipped for alphabetical order.
- Need to add support for Carbon Devtools (search `getDevtoolsProps` for an example).

Part 2 will most likely be Wednesday.

**Comment by AlexanderMelox** [comment]
@elycheea **The terminal itself does not include a way to interact or type on it. Wanted to check that this is intentional or if it’s something for the consumer to implement?**

We decided to design the web terminal so that the user has to pass in their own web terminal to use. Some teams have their preferred terminals and we wouldn't want to take away from that and make them redo everything they are used to. The WebTerminal component is only a shell for the terminal.

**Comment by glapadre** [comment]
### Part 2: 
@AlexanderMelox here are new comments from review with @qbi11y and @elycheea today.

## Engineering review
- Missing SASS imports for Button, OverflowMenu & OverflowMenuItem

## Standards
- Copyright header is missing on every source file that needs it (look at Card component for example)

## Testing
- Add test cases for accessibility 
- Missing test inputs on on all inputs for iconDescription. Do we need to add a check for this? Might be hard to test this..
- Code coverage is at 93% 
![image](https://user-images.githubusercontent.com/25260547/178808415-97920020-a7ab-473f-90f2-f92fb3935ec8.png)

## Documentation
-  Make sure to add all of the props on all of the controls for each of the types to make it consistent across patterns ('Default' has 2 controls, but then 'With Documentation Links' only has one control for example)
<img width="450" alt="Screen Shot 2022-07-13 at 1 56 50 PM" src="https://user-images.githubusercontent.com/25260547/178810867-f889f766-917d-46f1-9254-697dd8a05397.png">

**Comment by elycheea** [comment]
🎉 All that’s left is to actually move WebTerminal out of canary.

I believe you need to make this change in two places.
- `packages/cloud-cognitive/src/global/js/package-settings.js`
- `packages/cloud-cognitive/src/components/_index-released-only.scss`

@allcontributors please add @AlexanderMelox for code

**Comment by elycheea** [comment]
Released in 1.29.0
