### ISSUE TITLE
APIKeyModal: version with steps causes errors

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#1445]
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

The stories that utilize the version of this component with multiple steps cause the page to break.
> Is this issue related to a specific component?

APIKeyModal
> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected the default behavior of the multi step APIKeyModal examples/stories.
> What browser are you working in?

Chrome
> What version of the @carbon/ibm-cloud-cognitive package are you using?

Latest

## Steps to reproduce the issue

1. See stories for APIKeyModal with multiple steps

## Additional information

- Screenshots or code
- Notes
![image](https://user-images.githubusercontent.com/10215203/142039589-e16fc427-5fe9-4511-b6cd-eced30dce600.png)

**Comment by davidmenendez** [comment]
it looks like there's a bug with storybook (https://github.com/storybookjs/storybook/issues/11554#issuecomment-970636985) that's accounting for this. i'll follow up with them, but i don't think there's anything i can do at the moment. i think the best solution for the time being is just to hide the custom steps story, because otherwise it's basically impossible to show off the capabilities while this storybook bug persists.

**Comment by davidmenendez** [comment]
someone left a comment on that issue i linked above (https://github.com/storybookjs/storybook/issues/11554#issuecomment-970908541) for a potential solution, but it would involve messing with the babel config. i'm not sure if this is an avenue we want to go down. i'll open it up to the team for discussion.

**Comment by davidmenendez** [comment]
@dcwarwick found a solution
