### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#146]
This issue is to facilitate a discussion around defining a formal name for the package and repo that can be used going forward - The name `ibm-cloud-paks` isn't inclusive to components and packages that should serve the entire Cloud and Cognitive organisation.

Comments, discussion, ideas, and thoughts in the thread.

/cc @carbon-design-system/ibm-cloud-paks, @carbon-design-system/ibm-cloud-paks-design, @carbon-design-system/ibm-cloud-paks-development

**Comment by lee-chase** [comment]
I spoke with Adrian Jones, Sean Stopnik and @Levinson1 (David Levinson) yesterday and David is looking into this. 

I have suggested we go with a code name as opposed to using an organisational name, due to the changeable nature of org names.

I mentioned that Andy Gatford quite liked the idea of a play on Carbon 

e.g. 
- carbide - compound of carbon and metal
- carbite - not real but exists in games and part of a company name
- graphide - doesn't really mean anything
- graphene - thin sheet of carbon
- graphite  - crystaline carbon

Npm has 
 1 hit for carbide - a 5 year old v0.3.1 project with 3 weekly downloads
0 hits for carbite - 0 hits
0 hits for graphide - 0 hits but Graph IDE will match a lot of things on google
54 hits for graphene - a 5 year old v 0.1.2 project with 2 downloads per week
159 hits for graphite - a 2 year old project v0.1.4 with 30,000 downloads per week

Whatever we choose we should check npm and probably google too.

When a name has been selected we have a choice of how to use it.

- @carbon/carbide-components-react - a mix of @carbon/icons-react and carbon-componnts-react
- @carbon/carbide-components- would match @carbon/icons
- @carbon/carbide-react - would match @carbon/icons-react
- @carbon/carbide 

This namespaces us under Carbon so we should consult them first. David said he would check with @joshblack 

- @carbide/components-react - (my preferred)
- @carbide/components

Gives us our own namespace @carbide in which we could publish packages

- carbide-components-react
- carbide-components

No namespace, less popular with bigger libraries.

NOTE: We will also need to name the existing components e.g.

- @carbide/cdai-components-react
- @carbide/security-components-react

**Comment by SimonFinney** [comment]
Thanks @lee-chase - I agree we should use a codename, and I like the direction of `carbide`. 🎉 

For consistency with the direction of rest of the ecosystem, I suspect we should remain under Carbon's namespace. Given the entire repo is currently baselined with React, would `@carbon/carbide` be succint enough at a top-level? We could then do something like:

- `@carbon/carbide`
- `@carbon/carbide-cdai`
- `@carbon/carbide-ibm-security`

Or:

- `@carbon/carbide/cdai`
- `@carbon/carbide/ibm-security`

**Comment by vladbalanescu** [comment]
I think it's worth us going for this one `@carbide/components-react` to have our own namespace or `@carbon/carbide` if we really want to be under Carbon's namespace 👍

**Comment by asfordmatt** [comment]
Our repo is hosted under Carbon, so I think we should publish under the `@carbon` namespace (and agree the names with Josh)

If we go with a codename instead of `ibm-cloud-paks`, can we rename the repo to match?

**Comment by lee-chase** [comment]
> Our repo is hosted under Carbon, so I think we should publish under the `@carbon` namespace (and agree the names with Josh)
> 
> If we go with a codename instead of `ibm-cloud-paks`, can we rename the repo to match?

Definitely, it is something I was asked about yesterday but didn't want to push ahead without getting agreement from the Carbon team.

**Comment by Levinson1** [comment]
As Lee mentioned, we need to remove reference to Cloud Paks, Bedrock, etc. as they those name are too limiting. I reached out to Josh Black yesterday to see if Carbon has a standard (or would like to take this as an opportunity to establish one). Given Cloud and Cognitive are one of a few major groups (AI Apps, Watson Health) building/maintaining a PAL library, it makes sense to have a standard. Similar to the naming of the sites to "Carbon for...".

**Comment by SimonFinney** [comment]
On Security, we use `@carbon/ibm-security` (https://github.com/carbon-design-system/ibm-security#getting-started), and I also see 'Carbon for IBM.com' using a `@carbon/ibmdotcom-*` pattern (https://github.com/carbon-design-system/carbon-for-ibm-dotcom#getting-started).

If we can be confident that the naming won't change from 'Carbon for Cloud and Cognitive', we could follow an approach like `@carbon/cloud-cognitive`

**Comment by Levinson1** [comment]
"If we can be confident that the naming won't change"

That's the problem. We know the name will change eventually.

Since 2015 our org has been:
Middleware Design
Hybrid Cloud Design
Cloud, Data & AI Design
Cloud & Data Platform (Arin) and Cloud and Cognitive Design (Rob Thomas)

**Comment by asfordmatt** [comment]
> If we can be confident that the naming won't change from 'Carbon for Cloud and Cognitive', we could follow a similar approach, for example @carbon/cloud-cognitive

If we're just talking about a name for the existing CDAI components, I think something like `@carbon/ibm-cloud-cognitive` would be fine as they will hopefully be superseded by the new core package before the next org rename :)

**Comment by Levinson1** [comment]
I heard back from Josh and it does seem that the other orgs are simply using the @carbon/ibm--<bu> naming convention. I am fine with adopting that as long as we all agree to not be under any illusion that it will be outdated when the next org name change comes around.

**Comment by lee-chase** [comment]
So is this a democracy or are you telling us to use @carbon/ibm--cloud-cognative @Levinson1 ?

Which would also mean 
- @carbon/ibm--cloud-cognative--automation
- @carbon/ibm--cloud-cognative--cdai
- @carbon/ibm--cloud-cognative--security

Or are we at liberty to choose our own? The favourites so far seem to be between:
- @carbon/carbide-components 
- @carbide/components-react

**Comment by joshblack** [comment]
Just wanted to leave a note, as Simon and David shared above the convention right now is the "Carbon for ___" and `@carbon/ibm-<bu>` convention, e.g. "Carbon for Security", `@carbon/ibm-security`, but this convention can definitely be revisited.

In this case, it seems like it'd be "Carbon for Cloud and Cognitive" for the PAL, `@carbon/ibm-cloud-and-cognitive` but things like the package name can be shortened (like `@carbon/ibm-cnc`). It seems there are specific PAK packages that want to be built as well which may be complicating this?

In terms of naming, the only major design goals for the setup above are that:

- There is no confusion around if a project is a part of Carbon or not (e.g. in this org)
- There isn't confusion around the relationship of a project and Carbon, meaning one can reasonably tell if something is building on top of Carbon 

The "Carbon for ___" convention seemed to satisfy these goals, along with the package naming, but I totally understand if you all are running into limitations with this convention, or want to find something more durable than the BU naming scheme.

Happy to hop on a call to chat about this if I can help clarify anything or help in any way with the questions you might have 👍

**Comment by Levinson1** [comment]
Let's go with  @carbon/ibm-cloud-cognitive.
