### ISSUE TITLE
Tearsheet component throws useLayoutEffect warnings

### ISSUE THREAD

**Issue by David-Yuen** [carbon-design-system/ibm-cloud-cognitive#1640]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description
I'm not sure how accurate my understanding is, but I think this component is trying to render or execute something JS.. but because our application (and most ibm cloud applications) have server-side rendering for our pages, it fails to execute until it reaches the client side. 

> Describe in detail the issue you're having.
This component is trying to do something during server-side rendering, but it shouldn't.

> Is this issue related to a specific component?
Tearsheet

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expect to not see this type of warning. In comparison, like other components from Carbon, none of these throw warnings due to client vs SSR rendering.

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
latest 1.6.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Data Replication

## Steps to reproduce the issue

1. Use `Tearsheet` component in an application with server-side rendering.
2. The main page (or non-conditional nested components) should render the Tearsheet
3. Observe the server side logs when loading the application page

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

## Additional information

server-side terminal screenshot
<img width="1224" alt="Screen Shot 2022-02-14 at 3 08 23 PM" src="https://user-images.githubusercontent.com/37594705/153938526-1de5b98f-5947-45ce-a965-fa700449fdf2.png">

**Comment by dcwarwick** [comment]
Good catch. I'll need to think about this.

The hooks `useEffect` and `useLayoutEffect` do nothing on the server when using SSR, but `useLayoutEffect` is designed to run synchronously between generating the DOM layout and rendering it -- this can't be accomplished with SSR DOM, so that gives us two possible approaches:
1. Delay the rendering of tearsheets, by showing them in a `useEffect`, so they do not SSR and appear only on the client.
2. Accept the possible 'flicker' that might arise if the SSR DOM renders and is then adjusted by the code from the `useLayoutEffect`.

HOWEVER, since this hook was first added the tearsheet logic has been restructured quite a bit, and looking at it now I *think* that all the changes triggered by the code in the `useLayoutEffect` are making reactivity updates, which will themselves get applied through `useEffect`, _i.e._ asynchronously. I need to check this out carefully, but if that is the case then we can switch this `useLayoutEffect` to a `useEffect` and so avoid this issue entirely. I'll look into it.

**Comment by David-Yuen** [comment]
thank you for picking this up quickly, i appreciate it!

And yeah, i've only briefly read about the warning and how to resolve, it seems to suggest to delay the rendering or something.. but sounded like it should be resolved within the component. 

Anyways, i will be waiting for this to be resolved. Thanks again

**Comment by dcwarwick** [comment]
With v1.7.0 of `@carbon/ibm-products` the Tearsheet no longer uses `useLayoutEffect`, so the warning messages should be eliminated. Please check that, and if it is not fully resolved do reopen this issue so we can take another look.

**Comment by David-Yuen** [comment]
Yes, this has resolve the issue, thanks!

And thanks again for fixing this quickly, we really appreciate it!
