### ISSUE TITLE
Release Review for OptionsTile

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/ibm-cloud-cognitive#1656]
#1655

**Comment by matthewgallo** [comment]
## Review for release

### Readiness

- [ ] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [ ] A functioning component or components delivering those scenarios have been delivered and merged to main.
- [ ] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [ ] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [ ] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [ ] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [ ] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [ ] Components are functional components using hooks.
- [ ] Public components which produce DOM structures support className.
- [ ] Public components support a ref (via React.forwardRef).
- [ ] Public component supports a [Devtools attribute](https://github.com/carbon-design-system/ibm-cloud-cognitive/search?l=JavaScript&q=devtools&type=)
- [ ] All significant DOM elements have meaningful classes.
- [ ] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [ ] No warnings, errors or log messages in the console.
- [ ] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.
- [ ] Each public component SCSS lists all of the Carbon and C&CS components imported and used by the JavaScript code and explicitly imports the SCSS for each of these components.

### Standards

- [ ] No linter warnings or errors are produced.
- [ ] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [ ] All components utilizing motion must include reduced-motion queries for accessibility purposes - [read more here](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion).
- [ ] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [ ] Code is clear, maintainable and follows standard React practices and the [code guidelines](https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/master/docs/CODE_GUIDELINES.md).
- [ ] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [ ] There is a set of test cases for the components.
- [ ] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [ ] The tests validate the behaviors and interactions defined in the design where practical.
- [ ] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [ ] No warnings, errors or log messages in the test output.

### Documentation

- [ ] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [ ] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by janhassel** [comment]
@matthewgallo I checked with Christian Fritsche (as we are the designers of this component) and after the two bugs we identified (#1722 and #1725) this is approved from design side 👍

**Comment by elycheea** [comment]
### Engineering review
- OptionsTile is currently using `heading` as the heading — other components in our library use `title`. We should probably rename this to be consistent.
- `summary` looks like a new prop we haven’t used anywhere else before, but seems appropriate for its usage since it’s not quite the same as a description.
- `locked` and `lockedText` seem new — want to confirm that the expandable tile is still intended to expand when locked and that this state is a different case than `disabled`.
- `enabled` doesn’t clearly specify what it’s enabling — maybe we can rename this to `withToggle` or `includeToggle`.
- `headingId` should be renamed to `titleId` if we rename the heading prop.
- The props in OptionsTile and Static Options Tile are in a different order. May be better to keep them consistent.
- The responsiveness in Storybook seems like it could be improved at small screens — maybe set `min-width: 100%` and `width: 32rem` instead so that it passes when we test on the smallest screen size.
- We’re missing an import for the Carbon toggle SCSS.

### Standards
- Can we verify that where we’re using `rems` instead of spacing, that these are actually intended to be hardcoded rems?
- It’s a new year so we should update the second year in each of the OptionsTile files to include 2022. 🙌 

### Testing
Seeing one failed test for accessibility.
![image](https://user-images.githubusercontent.com/1717398/157102816-b34981a5-b0a0-4f85-88cb-bb527a044b3c.png)
@matthewgallo are trying to find the coverage report which we’ve moved. 😅 

### Documentation
Just need to add a CodeSandbox under [examples](https://carbon-for-ibm-products.netlify.app/?path=/story/overview-examples--c-4-p-gallery).

**Comment by janhassel** [comment]
@elycheea 

Thanks for the review. I opened a PR with the updates: #1750

> OptionsTile is currently using heading as the heading [...]

I tried to avoid `title` as it's a native HTML attribute but I agree that it should follow the standard established with all other components.

> [...] want to confirm that the expandable tile is still intended to expand when locked [...]

Yes, the tile should be expandable. It's different from a tile that has a toggle with is turned off in that the user can't change anyhting in a locked tile (including the toggle). It serves as an information of the current state / settings.

> enabled doesn’t clearly specify what it’s enabling — maybe we can rename this to withToggle or includeToggle.

This is a tricky one as `props.enabled = true` means there is a toggle and it is turned on, `props.enabled = false` means there is a toggle but it's turned off and `props.enabled = undefined` (or anyhting falsy) means there is no toggle. With your suggestions, does that mean you would split this into two props? From a developer experience standpoint I thought the current behaviour would be the cleanest.

> The props in OptionsTile and Static Options Tile are in a different order. May be better to keep them consistent.

This seems to be due to the first story setting a few more defaults which are then pushed to the top of the list. Is there a way to define the order of controls without setting defaults for all props that don't need defaults?

> Can we verify that where we’re using rems instead of spacing, that these are actually intended to be hardcoded rems?

Just checked again and fixed a couple. The remaining spacings should not use tokens. I added some annotations to hopefully make it clearer. Let me know if there is one that you're particularly concerned about!

> Just need to add a CodeSandbox under examples.

Is there a script that generates a new codesandbox example (like scaffolding a components) or should I copy an existing one (e.g. `Cascade`) and update it to reflect the usage of OptionsTile?

**Comment by matthewgallo** [comment]
I think sticking to the one prop `enabled` is ok, as long as it's documented clearly. So I think the last few steps are:
1. Creating a code sandbox example in `examples/carbon-for-ibm-products`
2. Making sure test coverage is at 100%, one of us will run the coverage report and update this issue to let you know

**Comment by matthewgallo** [comment]
![image](https://user-images.githubusercontent.com/10215203/157478142-e187a9f1-2511-4a87-b6a4-000069c29774.png)
Looks like there are a few more tests that need to be added. You can generate this report by running `yarn test:c4p /OptionsTile/ --coverage`, it will show you what parts of the component are not covered.

**Comment by janhassel** [comment]
@matthewgallo I just opened a PR for the test coverage (#1767) and for the codesandbox example (#1768). Let me know if we're missing anything else.
