### ISSUE TITLE
Data table: Align expandable rows to PAL pattern

### ISSUE THREAD

**Issue by johanna-koval** [carbon-design-system/ibm-cloud-cognitive#1922]
The component for the expandable row is not following the latest PAL guidance.
PAL guidance: https://pages.github.ibm.com/cdai-design/pal/components/data-table/expandable-rows/usage
<img width="1392" alt="CleanShot 2022-04-15 at 15 08 00@2x" src="https://user-images.githubusercontent.com/5809654/163622433-887dbf72-0af9-4176-be9b-e1cea6b18938.png">

**Is this issue related to a specific component?**
Data table https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1607

**Expected design:**

- Addd the padding for the expandable area
<img width="876" alt="CleanShot 2022-04-15 at 15 13 31@2x" src="https://user-images.githubusercontent.com/5809654/163622656-1290dedc-5970-407e-9d6f-b25c64ccd23a.png">

-Provide aligning options:

<img width="1075" alt="CleanShot 2022-04-15 at 15 15 05@2x" src="https://user-images.githubusercontent.com/5809654/163622830-071d4942-42f9-4ef4-b77a-c58cac9db445.png">
<img width="1134" alt="CleanShot 2022-04-15 at 15 14 58@2x" src="https://user-images.githubusercontent.com/5809654/163622832-a2264b2d-497d-49e7-ab0b-ac1fd6287de8.png">

**Comment by elycheea** [comment]
Hi @johanna-koval!

We were reading through the [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/expandable-rows/usage#how-to-lay-out-content) on alignment of content — this section looks more like recommendations for the developer using expandable rows rather than something for us to implement.

We will make the changes for padding but will likely leave the content alignment to the developer consuming this component extension.

**Comment by johanna-koval** [comment]
Hi @elycheea 
The padding (top, right, top and bottom) shown in the image should remain the same regardless of the dev/design preference for the internal layout or between content spacing
