### ISSUE TITLE
Revisiting motion libraries for component animations

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#1936]
## What will this achieve?

After working with motion on components in Carbon for IBM Products, we noticed that trying to animate elements that leave the DOM can be challenging. @matthewgallo has added utilities to help with this but they can quickly become buggy (relying on state and adding handlers in places to undo "onAnimationEnd" handler.)

We should consider Framer motion because it is easier to use and has a ton of features for reduce motion and hooks that the team can benefit from.

**Comment by elycheea** [comment]
Updated the title since we’re also going to be looking into Motion One.

Framer Motion on [Bundlephobia](https://bundlephobia.com/package/framer-motion@6.3.2) | Motion One on [Bundlephobia](https://bundlephobia.com/package/motion@10.7.2)
-----------------------|----------------------------
![image](https://user-images.githubusercontent.com/1717398/165780557-b750dbe6-ef0d-41bd-aa61-98022d62d1b8.png) | ![image](https://user-images.githubusercontent.com/1717398/165780998-5d551512-413d-4e7c-a07c-59074ae8668a.png)

**Comment by elycheea** [comment]
CSSTransitionGroup — some Carbon components don’t forwardRef so can be tricky to work with.

Motion One allows us to animate anything in the DOM — can use class or ID, but downside is does not allow mount/unmount animations.

Framer Motion is easier for mount/unmount and easy to learn.
- We can abstract layers to our own library code to be reused.
- Can only target elements if Carbon forward Refs — doesn’t really work well for animating a Carbon component itself.

Title animation for SidePanel has so much logic — a library would make them way simpler to work with.
Open and close is an example where AnimatePresence would help.

Lightweight version of Framer Motion might be viable.
