### ISSUE TITLE
Design Review: WebTerminal

### ISSUE THREAD

**Issue by AlexanderMelox** [carbon-design-system/ibm-cloud-cognitive#1958]
# Design Review Checklists

## Component reviews

When reviewing a component’s design, check that the pattern is closely followed,
and keep an eye on the component review checklist below.

Each component should be reviewed based on these criteria where applicable.

### Tips for a deeper design review

Reviewing a component’s UI correctness may be difficult by eye only,
particularly with color, sizing, paddings, etc. To be more thorough, we suggest
opening your console in your browser (right click + “Inspect”) and using your
element selection tool to look through the component’s styles. This will help to
catch differences in pixel size or slight color variations prior to component
release.

Any questions regarding the component’s compiled styles can be answered by your
developer.

**Tip** You should be able to copy and paste the section below directly into a
GitHub comment, then check where criteria passed, strike out where not
applicable, and add notes to each item where applicable.

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the
component developer\
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
maintainer\
- [ ] The component’s UI matches the pattern specifications set by the pattern
maintainer\
- [ ] The component’s motion matches the specifications set by the pattern
maintainer(s)\
- [ ] The UI produced is responsive, cross-browser, and responds to the currently
set Carbon theme.\
- [ ] Colors, themes, sizes and additional props are true and correct,
aligning with Carbon set tokens (unless otherwise specified by the pattern)\
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile
views

### Storybook

- [ ] A functioning component renders in Storybook\
- [ ] The Storybook displays multiple scenarios that show how the component can
be used\
- [ ] Changing props in the Storybook updates the component

**Comment by elycheea** [comment]
@AlexanderMelox Were we able to find a design maintainer for this issue?

**Comment by Laura-Marshall** [comment]
I can act as a design maintainer for this one. @AlexanderMelox, do you happen to have the original design handover document with the specs? The Figma kit was built off the code so this wouldn't be worth comparing to?

**Comment by AlexanderMelox** [comment]
@Laura-Marshall Yes,  I can find it for you

**Comment by Laura-Marshall** [comment]
### Standards

- [x]  All pattern updates/changes/iterations have been discussed with the component developer\
- [x]  Patterns have been approved by either DSAG or another approving entity

_*Note these are assumptions, I was not the designer who proposed this component_

### Pattern and behavior

- [ ]  The component behaves according to the guidelines set by the pattern maintainer\
- [x]  The component’s UI matches the pattern specifications set by the pattern maintainer\
- [x]  The component’s motion matches the specifications set by the pattern maintainer(s)\
- [x]  The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.\
- [ ]  Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)\ _(I don't know how to assess this properly in inspect mode, so I don't feel able to say either way. Visually, it looks correct)_
- [ ]  Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook
- [x] A functioning component renders in Storybook\
- [ ] The Storybook displays multiple scenarios that show how the component can be used\
- [x] ~~Changing props in the Storybook updates the component~~


### Comments

So I think there is opportunity to align this component further with the side panel. At the moment, the design specs show 24px either side, whereas code shows 16px. For standard side panels, 16px padding is used so although the code doesn't match design, I think the code should be maintained.

![image](https://user-images.githubusercontent.com/53219208/173868836-e6929b2f-7b88-40ae-8864-83f4d92abe8a.png)

Currently, the width of the web terminal is 584px. I wonder if it's worth changing this to align with one of the standard sizes of side panel. Large 640px or medium 480px are the closest options, and I don't think anything would be lost by making this 480px instead. 

The design documentation mentions being able to resize the panel by dragging it, which is not implemented in code. 

![image](https://user-images.githubusercontent.com/53219208/173871322-457c3713-2b39-4873-97a1-04b33a42226b.png)

Finally, design shows a loading state. I couldn't find a way to show this in the code.

![image](https://user-images.githubusercontent.com/53219208/173869691-ca548b70-e864-4308-ad0b-6a14ce18d34f.png)

**Comment by AlexanderMelox** [comment]
@Laura-Marshall We can definitely change the width to align with the side panel component. To get this right I will change the width of the web teminal to 680px? Also the loading state was removed because we are allowing the developer to pass in their own web terminal and don't want to intervene with those libraries loading states

**Comment by AlexanderMelox** [comment]
This is with the 480px, I think it's too small. I would hate to use a terminal on this small of a width. The lines would be wrapping a lot.
<img width="1443" alt="Screen Shot 2022-06-22 at 10 32 32 AM" src="https://user-images.githubusercontent.com/12755042/175055457-773d8404-1b82-472b-be3b-a23881713cfa.png">

This is the 640px. 
<img width="1438" alt="Screen Shot 2022-06-22 at 10 33 24 AM" src="https://user-images.githubusercontent.com/12755042/175055664-53cede91-7d1f-481a-853b-3a076d7d85da.png">

Most of the time, our users are using large desktop devices, so 480px can seem small on a larger desktop

**Comment by AlexanderMelox** [comment]
@Laura-Marshall Made a PR #2066

**Comment by Laura-Marshall** [comment]
Happy to close this!

**Comment by elycheea** [comment]
You can do the honors @Laura-Marshall  :)

**Comment by Laura-Marshall** [comment]
Don't seem to have the permission to close!

**Comment by elycheea** [comment]
@Laura-Marshall Oops. I should have known that! 😅  Closed!! Thank you @Laura-Marshall and @AlexanderMelox
