### ISSUE TITLE
export 'layout05' (imported as 'layout05') was not found in '@carbon/layout'

### ISSUE THREAD

**Issue by ginneapig** [carbon-design-system/ibm-cloud-cognitive#2113]
**WARNING** in ./node_modules/@carbon/ibm-products/es/components/PageHeader/PageHeader.js 314:37-45
export 'layout05' (imported as 'layout05') was **not found** in '@carbon/layout' (possible exports: baseFontSize, breakpoint, breakpointDown, breakpointUp, breakpoints, container, container01, container02, container03, container04, container05, em, fluidSpacing, fluidSpacing01, fluidSpacing02, fluidSpacing03, fluidSpacing04, iconSize, iconSize01, iconSize02, miniUnit, miniUnits, px, rem, size2XLarge, sizeLarge, sizeMedium, sizeSmall, sizeXLarge, sizeXSmall, sizes, spacing, spacing01, spacing02, spacing03, spacing04, spacing05, spacing06, spacing07, spacing08, spacing09, spacing10, spacing11, spacing12, spacing13, unstable_tokens)

Why is layout05 missing from @carbon/layout or does the name need to be updated in @carbon/ibm-products?

**Comment by matthewgallo** [comment]
This is most likely happening because you're using Carbon v11 with our component library. We do not _yet_ support v11, but are currently working on providing a release candidate for people to try out. Feel free to follow along with the following issues to see our progress:
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2020
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/2071
https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/1869
