### ISSUE TITLE
v1.34.0 is throwing framer-motion related error

### ISSUE THREAD

**Issue by jainshravan123** [carbon-design-system/ibm-cloud-cognitive#2378]
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
v1.34.0 is throwing framer-motion related error

## Detailed description

> Describe in detail the issue you're having.
It @carbon/ibm-products that has a child dependancy on framer-motion which seems to be causing a failure in our builds. 

npm ls framer-motion
OUR_MODULE@15.0.603 PATH_TO_OUR_MODULE
└─┬ @carbon/ibm-products@1.34.0
  └── framer-motion@6.5.1 

It's throwing the following error.

```
./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
```

Looks like it was caused because of this [PR](https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/2314/files#diff-ec299191490e813772878f9ec7b5cd5fb9c754583b687b5e0e6483d9db2dfb48).

As of now we had pinned the @carbon/ibm-products to `v1.33.0` and our component is working fine. 

> Is this issue related to a specific component?

Upgrade of framer-motion.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
It should have worked without error. 

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

v1.34.0

**Comment by matthewgallo** [comment]
Hey @jainshravan123, are you using create react app (`react-scripts`)? We've found that upgrading to `react-scripts@5.x.x` resolves this issue.

**Comment by jainshravan123** [comment]
Hi @matthewgallo 
No we aren't using react-scripts.

**Comment by obambrough** [comment]
I've also run across the same compilation issue due to framer-motion, except it's our Storybook that won't compile (while our next.js application does.)

```
react: 17.0.2
@storybook/react: 6.4.13
@storybook/addona11y: 6.4.13
@storybook/addon-essentials: 6.4.13
storybook-addon-next-router: 3.1.1
sass-loader: 10.2.0
```

We have other devDependencies, I don't know which ones may be related to our use of Storybook so I've not listed them.

We have a .storybook/webpack.config.js that just contains a few helpful aliases.
We have a .storybook/main.js that configures the path for the stories, the addons (listed above) and sass-loader.

After upgrading to ibm-products 1.34.0 when running storybook it'd fail with several errors like this:

```
ERROR in ./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs 93:36-50
Can't import the named export 'Fragment' from non EcmaScript module (only default export is available)
 @ ./node_modules/framer-motion/dist/es/index.mjs
 @ ./node_modules/@carbon/ibm-products/es/components/SidePanel/SidePanel.js
 @ ./node_modules/@carbon/ibm-products/es/components/SidePanel/index.js
 @ ./node_modules/@carbon/ibm-products/es/components/EditSidePanel/EditSidePanel.js
 @ ./node_modules/@carbon/ibm-products/es/components/EditSidePanel/index.js
 @ ./node_modules/@carbon/ibm-products/es/components/index.js
 @ ./node_modules/@carbon/ibm-products/es/index.js
 ...
```
 
Based off of this Stack Overflow posting (https://stackoverflow.com/questions/69769360/error-importing-framer-motion-v5-in-react-with-create-react-app) I'm able to get it to compile by adding the following into our .storybook/main.js 

```
config.module.rules.push(
  {
    test: /\.mjs$/,
    include: /node_modules/,
    type: 'javascript/auto',
  }
);
```
I don't know what the root-cause of the issue is and would rather not include this work-around if possible.

**Comment by lee-chase** [comment]
@obambrough @matthewgallo this is not a work around. The version of Framer in use requires javascript modules, in version 4 of Webpack it is supported through adding the above config. In version 5 it is supported by default. 

Upgrading react-scripts is one way to upgrade WebPack.

As we are unlikely to downgrade of the version of Framer, users will need to ensure they support ES Modules. @elycheea perhaps raise a documentation issue and close this one.
