### ISSUE TITLE
Datagrid design review: Row height settings

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2503]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Virginia Nicholson, Sammy Schuckert
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/settings/usage/) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-rowheightsettings)

---

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [x] The component behaves according to the guidelines set by the pattern
      maintainer
- [x] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [x] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by sammyschuckert** [comment]
In general the implementation works as expected and follows most of the PAL guidance. I needed to very nit-picky to find inconsistencies and issues.

### 1. Order of size settings in the menu 
The order of the size settings is descending in the storybook while the PAL guidance uses a ascending order for the size settings.

![image](https://user-images.githubusercontent.com/6014057/211615792-9ab3872e-0652-4a12-b2e8-56fe7053058c.png)

### 2. One size setting labeled wrong and "Small" setting missing
In the Storybook the default rowSize array is listing size settings in the wrong order and labels "Extra small (xs)" as "Small", hence "Small (sm)" is missing.

![image](https://user-images.githubusercontent.com/6014057/211616359-7df000b5-4067-4123-b718-0972fcb77eaf.png)

### 3. Placement of the settings button
The PAL guidance is very specific on the placement of the settings button, I suggest we suggest we should make sure the storybook reflects this placement as described [here](https://pages.github.ibm.com/cdai-design/pal/components/data-table/settings/usage/#placement). 

> The settings icon should be placed to the right, directly to the left of any CTA button or flush to the table edge. The flyout stays open until the user closes it by clicking on the icon or outside the flyout.

![image](https://user-images.githubusercontent.com/6014057/211617117-16bfdcfa-e80b-43cd-9d5c-3708b5a37c9c.png)

### 4. PAL guidance unspecific on "min-width", code component seems to have a "max-width" when using the dense table header
The mock-ups used for the PAL guidance imply that the flyout has a min-width, but the guidance isn't explicitly stating this. The code component doesn't have a min-width, but when switching to the dense header on the table it looks as if the flyout has all of a sudden a max-width? I'm unsure about this inconsistency. Maybe Virginia (couldn't tag her) can provide more details on this.  

![image](https://user-images.githubusercontent.com/6014057/211617585-a565396f-a83a-4ec9-840f-2f9cca4ff39e.png)

### 5. Suddenly appearing "(default)" label which isn't described in PAL guidance
When I changed the rowSize array in the storybook, the "Large" size setting all of a sudden was labeled as the "(default)". Which I couldn't find in the PAL guidance as a requirement. I also couldn't reconstruct how I made this label appear as it is not there when reloading the storybook. Might be something for Virginia (couldn't tag her) to provide guidance and from a development perspective to investigate what's causing it to suddenly show up after changing the array. 

![image](https://user-images.githubusercontent.com/6014057/211622683-6faace00-8b87-4609-81ea-8ea799840376.png)


### 6. Usage of multi-line content in one column
The PAL guidance is to not offer row size settings when having one or more columns with multi-line content. In the storybook example table we are having one column with multi-line content. This could potentially be confusing, hence I suggest we should remove the multi-line column in the storybook example table. 

![image](https://user-images.githubusercontent.com/6014057/211620575-6ef0663f-bd7a-4cbe-ad1a-46ce7f172427.png)

**Comment by vsnichols** [comment]
Hi @sammyschuckert sorry for the delayed response! This looks great and I agree, there are very few issues here.

### 1. Order of size settings in the menu
No need to fix

### 2. One size setting labeled wrong and "Small" setting missing

- Ideally we should have both small and xs
- If we have to choose, we should discard the xs height and display the true small height (32px). This height is less likely to break items within the table.

### 3. Placement of the settings button

Yes if you are able to update the react storybook that would be great.

### 4. PAL guidance unspecific on "min-width", code component seems to have a "max-width" when using the dense table header

- I was not able to recreate the rightmost image below where the text wraps
- The flyout seems to have a fixed width which is as expected
- I do not think we need a min/max width. The flyout should just be large enough to contain each option on one line without wrapping.

![211617585-a565396f-a83a-4ec9-840f-2f9cca4ff39e](https://user-images.githubusercontent.com/39408106/215216457-decdba68-6f85-438f-be41-22c50cd2ede6.png)


### 5. Suddenly appearing "(default)" label which isn't described in PAL guidance

Not sure why "default" label is appearing, was not able to recreate. We don't need it and should omit it.

### 6. Usage of multi-line content in one column

Agreed, let's fix it so that none of the columns have multi-line content in the storybook.

### 7. Background color of settings icon section of flyout 

When the flyout is open, the area behind the part of the flyout that has the settings icon should be the same color as the rest of the flyout when user's mouse is not hovering over it.

<img width="1189" alt="Screenshot 2023-01-27 at 4 31 25 PM" src="https://user-images.githubusercontent.com/39408106/215218659-6ba6a532-43e6-429c-8419-c45a48bbd189.png">

**Comment by elycheea** [comment]
### Multiline content
This was added specifically for the scrolling behavior, but agree it makes sense to remove from this particular story since multiline wrapping isn’t optimized for all row heights (especially not `xs` through `md`).

### Default label
The naming of the rowSize labels can actually be set in the `rowSizes` control. Usually if you change these, it’ll add the new value in the URL which is why it doesn’t update on refresh. :)

![image](https://user-images.githubusercontent.com/1717398/218797789-37e1c0a7-7743-4a71-9cac-a3ea656e81d4.png)

We have some of these in David’s PR for #2625 but will fix the background color!

**Comment by elycheea** [comment]
@sammyschuckert @vsnichols With the latest changes merged, I’m going to close this as complete and open a release review for row height.

#2606 #2607 still need design reviews though. @sammyschuckert if you’d like to help with one of these, @Ratheeshrajan may be available to do a design review earlier in the day. Otherwise, Virginia, Ashley, and I can probably find time to make this work. 🖖
