### ISSUE TITLE
Datagrid design review: Inline editing

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/ibm-cloud-cognitive#2506]
## Design review

- Component epic #1607 #2499
- Designers/reviewers: Jennifer Jennings (@jjennings7)
- Links: [PAL guidance](https://pages.github.ibm.com/cdai-design/pal/components/data-table/inline-editing/usage) / [Storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary-extensions-inlineedit)

---

### Standards

- [x] All pattern updates/changes/iterations have been discussed with the
      component developer
- [x] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern
      maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern
      maintainer
- [x] The component’s motion matches the specifications set by the pattern
      maintainer(s)
- [x] The UI produced is responsive, cross-browser, and responds to the
      currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning
      with Carbon set tokens (unless otherwise specified by the pattern)
- [x] Paddings/margins/spacings are true and correct, in both desktop and mobile
      views

### Storybook

- [x] A functioning component renders in Storybook
- [x] The Storybook displays multiple scenarios that show how the component can
      be used
- [x] Changing props in the Storybook updates the component

**Comment by matthewgallo** [comment]
• Would be helpful to include variant with selectable rows (include `$ui-05` border around selected row)
• Add note about what columns use validation
• Complex cells are missing

**Comment by elycheea** [comment]
Re-assigning from Matt to @Ratheeshrajan 🚀

**Comment by jjennings7** [comment]
@matthewgallo @elycheea @Ratheeshrajan I checked the color tokens the best I could using Inspect in my browser and Carbon Dev Tools, and I found a few discrepancies:
| Interactive states      | Background Tokens | Implementation in Storybook |
| ----------- | ----------- | ----------- |
| Editable cell      | Background: $field-01 | $ui-01 |
| Cell hover   | Background: $hover-selected-ui       | $active-ui |
| Active filled cell      | Background: $active-ui <br> :rotating_light: think the documentation is wrong | $field-02 |
| Focus cell      | Background: $field-01 | $active-ui |
| Focus cell      | Text color: $text-02 | $text-01 |
| Focus cell      | Edit icon: $icon-02 | $icon-01 |

- For the mismatch on the `Focus cell` background, I think @matthewgallo mentioned it was changed intentionally? In the documentation, it's a light background but in the Storybook code, it's dark. If we're using the dark, we'll need to update the documentation for the background and corresponding text and icon colors. 
- The `Active filled cell` background seems to need updating in the PAL as well, it's calling out a dark background color which makes no sense and doesn't match the example images. 
- Not related to color, we mentioned maybe adding a tip somewhere in the storybook regarding the "edit" icons and when they do and don't appear: if less than half the cells are editable, show icon. If more than half are editable, don't show the icon.

**Comment by jjennings7** [comment]
@davidmenendez 
I only see one remaining issue, which is a problem in the documentation too as noted above:

Active filled cell is spec'd in the [PAL](https://pages.github.ibm.com/cdai-design/pal/components/data-table/inline-editing/usage#cell-states-and-structure) to be Background: `$active-ui`. This token uses gray-30 in g10 theme and seems to be an error, when you compare to the graphics which show the background as white:
![Screen Shot 2023-02-06 at 11 03 31 AM](https://user-images.githubusercontent.com/48838320/217063760-0f2aca97-418c-4841-bc14-d7df091f811c.png)
![Screen Shot 2023-02-06 at 11 03 57 AM](https://user-images.githubusercontent.com/48838320/217063782-0b0cd1be-9078-4ecb-982e-28dc070a6fd7.png)


In your implementation, you're using `$field-02` rather than `$active-ui`, but neither is correct. Pease use `$field-01` (unless you can recommend a more appropriate token that's white/#ffffff) so we get a white background to match the PAL graphics rather than `$field-02` which uses gray 10. I'll get someone to update the token in the PAL documentation.

Here's one example from a[ PAL graphic](https://pages.github.ibm.com/cdai-design/pal/components/data-table/inline-editing/usage#edit-mode) that shows the active background as being white:
![Screen Shot 2023-02-06 at 11 17 37 AM](https://user-images.githubusercontent.com/48838320/217064571-b6e5d503-3f68-4e9f-8bac-3a96e73fc17b.png)

**Comment by elycheea** [comment]
@jjennings7 It looks like we’ve addressed changes here. If you’re good with the updates, we can close this out. 🙌

**Comment by jjennings7** [comment]
Yes, I think everything has been addressed. Thank you!
