### ISSUE TITLE
Release review

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#272]
This issue is to facilitate a discussion around defining a formal process for conducting release reviews on individual components and patterns.

Comments, discussion, ideas, and thoughts in the thread.

/cc @carbon-design-system/ibm-cloud-cognitive , @carbon-design-system/ibm-cloud-cognitive-design, @carbon-design-system/ibm-cloud-cognitive-development

@matthew-chirgwin @vladbalanescu @asfordmatt @moores2 @davidmenendez @matthewgallo @lee-chase @SimonFinney 

As a starting point the technical sync meeting discussed:
- 100% code coverage
- E2E testing
- API - Are Dev happy with props, methods and events. A specific query about API bloat due to the need to allow all strings to be changeable. The topic of providing translation for fixed strings e.g. OK.
- Use of or tested in a product or product team?

**Comment by lee-chase** [comment]
Personally, I think we should aim for 100% test coverage and check the storybook and it's doc tab.

With regards to the API we should answer the question. Are we likely to need to break this before v1.

**Comment by SimonFinney** [comment]
Thanks @lee-chase - I'm all for defining a threshold for unit tests to ensure we have baseline coverage, as long we're not sacrificing the quality of tests in favor of hitting the numbers. Perhaps we should expand the criteria to include whether it's meeting appropriate use cases and that all inputs and outputs work as expected for consumers?

One thought on the API - I wonder if we should also verify against consistency with similar props in Carbon, as well as our own codebase.

**Comment by lee-chase** [comment]
In summary:
- consistency (the APIs look similar, internally and to Carbon) - NOTE: Carbon sometimes uses node instead of string prop to add flexibility
- testing: coverage above X% yet to be defined
- stories covers designed scenarios
- design has signed off the current version
- Doc tab covers designed scenarios.
- Doc tab includes metrics like test coverage, usage when data available, status any missing or incomplete functionality
- Codesandbox examples - may need a pro account.

**Comment by lee-chase** [comment]
Being discussed here to progress https://ibm.ent.box.com/notes/772354757139

**Comment by lee-chase** [comment]
Andrea Garcia -

> List of standards to be met in order to consider a component or pattern implementation complete and to make it available to the public
> 
> https://github.ibm.com/IBMPrivateCloud/BedrockServices/blob/master/AdopterGuides/CommonUXStandardsAdoptionGuide.md

**Comment by lee-chase** [comment]
Perhaps as part of thie @SimonFinney we can also document the relationship between the various packages we currently have, or even just up add a description to each README.

**Comment by SimonFinney** [comment]
> Perhaps as part of thie @SimonFinney we can also document the relationship between the various packages we currently have, or even just up add a description to each README.

Good point! I have an idea for this based on https://github.com/carbon-design-system/carbon#getting-started , and I can submit a quick PR for discussion

**Comment by lee-chase** [comment]
Not sure if this is applicable to React as other frameworks but avoiding use of standard HTML attribute names for anything other than their standard behaviour is not a bad idea.

**Comment by lee-chase** [comment]
@SimonFinney I wonder if it would make sense to do away with experimental, add feature flags to our main package and publish multiple versions:

- @carbon/ibm-cloud-cognitive@latest
- @carbon/ibm-cloud-cognitive@canary - @latest + pending PRs

Only with the 'experimental' feature flag set components marked as experimental are exported from the package index.js. 

The compiled CSS will have a bit of extra weight but otherwise would not be impacted.

The reason I added the @canary is because one of my colleagues indicated a rapid turn around might be needed for devs to not drift off and create private variants. Perhaps there is some middle ground to be had between all @latest and @canary, maybe further feature flagging.

**Comment by SimonFinney** [comment]
Because we don't explicitly cut releases, the current setup is essentially a canary build. I'd love to hear more about what you mean by including pending PRs - is this a manual process?

**Comment by dcwarwick** [comment]
Items discussed above now opened as issues under a new epic: #366. Closing this issue.
