### ISSUE TITLE
Cards: Expressive type - Design feedback

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#380]
Please size the issue once design feedback is received.

**Comment by JohannaSuarezKoval** [comment]
The expressive card looks great! 
I have a few comments on things that need to be adjusted following the component guidelines. Please feel free to reach out if any of these points need more clarity:

1. Since card size increments only by 4 columns, could we get controls in the storybook by size (small-4col, medium-8col, large-12col, max-16col)  instead of allowing number input? This way, we avoid things like 1, 2, 3, 5, etc columns cards. Side Panel has a similar control for size.
<img width="1434" alt="Screen Shot 2021-03-01 at 4 51 54 PM" src="https://user-images.githubusercontent.com/5809654/109563977-77ef4600-7aae-11eb-874d-64939920427f.png">

2. Ratios determine image size in the expressive card, so we shouldn't include fixed pixel (600x400) images as an example. I wonder if we can include some controls for image ratios. This will vary depending on the placement. For the left placement, the image has to be part of the card size column count.  Please see these examples: https://ibm.invisionapp.com/d/?redirHash=#/console/15373359/319889226/preview?scrollOffset=0

3. There should be a 2px spacing between the label and title.
<img width="649" alt="Screen Shot 2021-03-01 at 5 02 12 PM" src="https://user-images.githubusercontent.com/5809654/109565041-e7196a00-7aaf-11eb-8d5d-349a3ff7fcdb.png">

4. Button size for expressive cards has been determined to be field size (40px). Right now it is default size (48px).
<img width="823" alt="Screen Shot 2021-03-01 at 5 02 44 PM" src="https://user-images.githubusercontent.com/5809654/109565097-f993a380-7aaf-11eb-92af-3da2a5e7ac78.png">

5. Ghost buttons are the default button style for the secondary action. Can we leave that as the selected default in "secondaryButtonKind"?

6. Clickable cards need the hover state please see reference here: https://pages.github.ibm.com/cdai-design/pal/components/card/expressive/usage#action-zones

7. Clickable cards shouldn't include internal links, so I don't think the last variation is necessary.

8. In addition to having a `label + title` option, could we also have include variations of `tittle+caption` and `just label` in the title block?
<img width="544" alt="Screen Shot 2021-03-01 at 5 05 47 PM" src="https://user-images.githubusercontent.com/5809654/109565405-67d86600-7ab0-11eb-92b3-9020fdb4968c.png">


Please let me know if you have any question

**Comment by JohannaSuarezKoval** [comment]
So exciting how this card is taking shape! 
Just a few details that I see in this last version:

- sm option makes the card 16col instead of 4col

- lg makes the card 4 col instead of 12col

- All the options under `ColumnSize` control are showing the number 4 after the size. Can it be adjusted to: sm-4, md-8, lg-12, max-16
<img width="327" alt="Screen Shot 2021-03-09 at 3 48 57 PM" src="https://user-images.githubusercontent.com/5809654/110536036-fcfddf00-80ee-11eb-9fae-1b7f15bc796d.png">

- The size sm should be disabled for the left media format, since the media is part of the column count 4col size does not give space for media to the left
<img width="334" alt="Screen Shot 2021-03-09 at 3 49 57 PM" src="https://user-images.githubusercontent.com/5809654/110536147-20c12500-80ef-11eb-9d26-c9c287333921.png">

- Now that the `ColumnSize` control was added, can the `cols` control be removed?

- suggestion: the media position control can replace having `With media` and `Media Left` as separate types. It could be just `With Media`  and leave the `MediaPosition` control at the top.

Thanks!
