### ISSUE TITLE
ES and LIB bundles include tests 

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#440]
This may be due to inconsistent use of .spec.js, .test.js and other variants for test file names.

**Comment by dcwarwick** [comment]
@lee-chase Actually, it turns out this is because babel globs for --ignore only support simple * and ** for whole slugs in pathnames, so globs like "**/*-test.js" are never going to work. They don't work for Carbon either, btw, and carbon-react ES and LIB bundles also include miscellaneous stories and tests. I suggest therefore that the patterns we settle on are _ComponentName_.test.js and _ComponentName_.stories.js, as these will make robust babel ignore patterns.

**Comment by lee-chase** [comment]
@joshblack FYI Dave's comment above.
