### ISSUE TITLE
Storybook props tables not rendering

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/ibm-cloud-cognitive#457]
## What package(s) are you using?

- [x] Cloud & Cognitive
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

The props table within the docs tab in storybook are not rendering for all components I've noticed recently.

**Comment by davidmenendez** [comment]
This issue is being caused by the canary conditional at the top of the component. this can be fixed by moving the conditional to inside the component function. for example-

```
export const APIKeyModal = () => {
  ...
  if (!pkg.isComponentEnabled(componentName)) return <Canary component={componentName} />
  return ...
};
```

cc @lee-chase @dcwarwick

**Comment by dcwarwick** [comment]
The downside of moving the conditional to inside the component function is that various bits of React, like useState and useEffect, cannot be used inside conditional branches: they must occur in the same sequence in all circumstances. So if the conditional is moved inside the component function, it needs to move all the way to where we are just about to return the render function, and can't enclose any preparatory work. This is quite intrusive.

If we are going to have to execute most of the component function, then perhaps we should just accept that and go for maximum convenience. It occurs to me that we don't really need to worry about performance or tree-shaking, since using a component that will render as Canary is not a production scenario -- the key thing is that components that are NOT Canary should spend an absolute minimum of time and distraction checking that they are released. I experimented with a number of ways of arranging this, and the pattern I thought looked neatest and had the shortest path for production use is to export the component with a `let` rather than a `const` and then simply reassign a Canary if we're not released. Thus:
```js
export let Component = (prop1, prop2, ...) => { ..... return <stuff.....>; }

if (!pkg.isComponentEnabled(componentName)) {
  Component = () => <Canary .../>
}
```

In fact, to minimise what needs to appear in each file, I've made a little function in settings.js to do this check. That means each component doesn't need to import Canary and include the logic. It just calls one function in settings.js, and if the component is enabled this imposes a minimum of extra weight (one function return on top of checking the status). If the component is not enabled we've created then discarded a component needlessly, but as noted above this is already a failure situation and not part of a production scenario. Tree-shaking should ensure that all components not used are not packaged up, whether they would have rendered as Canary or not.
