### ISSUE TITLE
Component and pattern versioning

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#48]

**Comment by lee-chase** [comment]
During a CDAI meeting yesterday it was noted that as the patterns evolve it will become necessary to version them to reflect the latest design/features.

Andrew Gatford indicated that patterns will be versioned individually.

This lead to the suggestion that we have one package per pattern which will allow individual pattern updates to be published without affecting others.

**Comment by SimonFinney** [comment]
Thanks! @dbrugger How might this affect the current setup of the monorepo?

**Comment by andrea-gm** [comment]
Can we close this issue?

**Comment by SimonFinney** [comment]
It has been inactive since August 6, so my gut says yes

**Comment by andrea-gm** [comment]
@lee-chase I think I recall us talking about this and I thought it was resolved, but we may not have documented the outcome. I believe we said patterns will not have individual packages, correct?

**Comment by lee-chase** [comment]
@andrea-gm  the decision was to stick with the status quo I believe. Essentially we can always switch strategy later but now it would be a distraction.

The options are:
1. One package per component allowing different patterns to be updated without forcing the adoption of multiple new patterns at once. Not current Carbon behaviour, but they are interested and have offered to work with us on tooling (or at least Josh Black has).
2. Status quo. Try not to introduce breaking changes but otherwise release patterns as one package.

**Comment by andrea-gm** [comment]
I am closing this issue for now, we can open it up again if the strategy changes
