### ISSUE TITLE
Storybook utilities

### ISSUE THREAD

**Issue by SimonFinney** [carbon-design-system/ibm-cloud-cognitive#49]

**Comment by SimonFinney** [comment]
Acceptance criteria to be defined in GitHub by owner in collaboration with group

**Comment by SimonFinney** [comment]
Carbon just released some really nice updates to their Storybook documentation that leverages `@storybook/addon-docs` - https://react.carbondesignsystem.com/?path=/docs/accordion--accordion

**Comment by lee-chase** [comment]
The addition of the storysource addon in https://github.com/carbon-design-system/ibm-cloud-paks/pull/82 is because neither Docs nor ‘Show Info’ show the actual story which is useful when the story has state.

It is interesting to note that both Docs and ‘Show Info’ appear to display “source” for just the component under test as if reconstructed from the props.

As a bonus ‘Show info’ appears to use the live state of the story. Docs on the other hand displays the displays both the component under test and the source at the same time, but does not update the source.
