### ISSUE TITLE
Importing pkg from ESM module breaks Jest test cases

### ISSUE THREAD

**Issue by sauravazad** [carbon-design-system/ibm-cloud-cognitive#508]
## What will this achieve?
Importing pkg from ESM module breaks Jest test cases

eg:
```
import { pkg } from '@carbon/ibm-cloud-cognitive/es/settings'
pkg.component.Tearsheet = true
```

When running Jest test cases it throws below error 
![image](https://user-images.githubusercontent.com/3856934/112131442-93ea9100-8bef-11eb-8daf-007baf190cc9.png)

## Additional information
Importing from CommonJS module works fine 

import { pkg } from '@carbon/ibm-cloud-cognitive/lib/settings'

**Comment by lee-chase** [comment]
@sauravazad can you supply version numbers and ideally a codesandbox https://codesandbox.io/dashboard/all/?workspace=7d09c446-5d37-4748-92d5-3d510c6572d4

**Comment by lee-chase** [comment]
NOTE: I believe @sauravazad is using "@carbon/ibm-cloud-cognitive-experimental": "^0.21.2" which is two weeks old. 

I have requested they try the latest.

**Comment by sauravazad** [comment]
I am still getting the issue with Package version: "@carbon/ibm-cloud-cognitive": "0.28.9" .

Let me create a codesandbox .

**Comment by dcwarwick** [comment]
The problem here is that Jest runs under Node.js and uses CommonJS by default for module loading, not ESM. The difficulty is that when reaching into a package for anything other than the main entry point the import path has to explicitly choose whether to go for es (ESM) or lib (CommonJS).

@sauravazad you can work around this by:
 * (1) ensuring you have an up-to-date Node.js. Anything >13.2 should be fine. 14.16.0 is the current stable version. With a newer version of Node.js the error message should go away, but you will not yet get a usable Tearsheet...
 * (2) explicitly asking for the es version of all imports from @carbon/ibm-cloud-cognitive. _i.e._ in line 10 you would change that to `import { Tearsheet } from '@carbon/IBM-cloud-cognitive/es'. That will mean that everyone loads everything from the es version not the commonjs version, and this should work for you in browsers and in jest tests.

Can you let me know if you're able to do that, and it works for you?

**Comment by YuriBarssi** [comment]
@lee-chase @dcwarwick I'm facing similar issues, and I'm currently in "@carbon/ibm-cloud-cognitive": "^0.34.6", 
I'm trying to use the experimental items (SidePanel and UserProfileImage), and it looks great in Storybook. But Jest complains about it if I use ES. So not sure if like these components are not offered in the /lib folder, just on the es. If I toggle the import, Jest works well but I get that 'component experimental' message and they do not render.

In other words: 
- If I do `import { pkg } from '@carbon/ibm-cloud-cognitive/ES/settings';` the app works, but Jest does not.
- If I do `import { pkg } from '@carbon/ibm-cloud-cognitive/LIB/settings';` the app no longer works, but Jest runs OK.

We could see that the lib folder is transpiled, so I found a workaround by doing the following:
- Adding `transformIgnorePatterns: ['./node_modules/(?!@carbon/ibm-cloud-cognitive/es/).+\\.js$'],` in the jest.config.js file
- Creating babel.config.js with `module.exports = { presets: ['@babel/preset-env'] };`

**Comment by dcwarwick** [comment]
All components are offered in both /lib and /es -- these are just differently transpiled versions of each other. If Jest is "complaining", this may be because you are using an older version of node.js -- the capability to load ES modules directly was adding in node.js version 13.2 I believe, so if you are on the current LTS (fermium, currently at 14.16) you'd be fine, but older versions not so much.

HOWEVER I think you're last thought is potentially a winner -- we only recently added the package settings to the master export set, but now we've done that I think `import { pkg } from '@carbon/ibm-cloud-cognitive';` should work, and that would mean that both web bundlers and jest/node tools would load the settings from the same place as all the rest of the components, entirely automatically! I will do some testing of that. If you have a chance to try it, perhaps you could let us know if that works? It would be a much simpler approach all round!

**Comment by andrea-gm** [comment]
@YuriBarssi were you able to resolve the issue? can we close this one?

**Comment by YuriBarssi** [comment]
@andrea-gm @dcwarwick I thought you were going to test this possibility, then ask me to confirm if it has been fixed. Sorry, I misunderstood.

No it does not work for me. Doing `import { pkg } from '@carbon/ibm-cloud-cognitive';` shows some error for me. As if the pkg was not exported this way (es/settings do work though)

https://codesandbox.io/s/gracious-dream-ixgkv?file=/src/config.js

**Comment by sauravazad** [comment]
It has been been resolved in latest release.
