### ISSUE TITLE
Generate an API key

### ISSUE THREAD

**Issue by carrenelloyd** [carbon-design-system/ibm-cloud-cognitive#56]
Catalog # 10

[Link to Design ](https://www.carbondesignsystem.com/community/patterns/generate-an-api-key/)

**Maintainers**
Vikki Paterson, Chloe Poulter

[Working code](https://pages.github.ibm.com/cloud-integration-design/ide-components/?path=/story/production-ready-ide-api-key-generation-component--with-core-configuration)

**Comment by lee-chase** [comment]
@vikkipaterson can you comment as to the status of the design it was marked as 'status: refining' by @carrenelloyd

**Comment by davidmenendez** [comment]
@vikkipaterson @chloepoulterdesign this component is now ready for design review https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-apikeymodal--standard

**Comment by chloepoulterdesign** [comment]
Thanks David!

In `API Key modal > standard`:
1. I think the verb on the button should be `Generate` - ideally `Generate API key` rather than the current `Add API key`
2. I believe that while text in a modal should have a 20% margin on the right hand side, fields should be full-width.
3. The helper text which reads `Providing the application name will help you idenfity your api key later.` should have less padding above it (it should be closer to the field) and API should be capitalised. 
3. The "generating" state isn't quite right - when a user has filled in the name and clicks "Generate API Key", both the "Generate API Key" button and the "Application name" field should have a disabled-state - so that the user can't click the button or change the contents of the field while the key is being generated
4. Have you taken any direction on the keyboard tabbing order? I think as a keyboard user, when the modal opens, I would expect the "application name" field to have focus - so i can start typing immediately. Then, when I'm done typing, I would want to hit "enter" to activate the "generate an API key" button. Alternatively, if I hit "tab", I would expect focus to be applied to the "Generate an API key" button so that I could activate it next.
5. While the key is generating, I think the loading text with the spinner should just say "Generating..."
6. Once the key is generated, I think the primary button text needs to be "Copy & close" per some complaints about its' current text in [Slack](https://ibmapim.slack.com/archives/C0M053VPT/p1599658565344400?thread_ts=1599589238.319800&cid=C0M053VPT)

In `API Key modal > minimal`:
1. The button to open the modal is missing
2. There is no loading state in this option - what if I click the button to launch the modal, but it takes a moment to generate and then opens? I think we need to include the "Generate API key" button, which becomes a "Generating" message, and then opens the modal.
3. The field which displays the generated API key is not the same as the password-styled field in the "Standard" option
4. The font size and styling of the "This is your unique API key and is non-recoverable" text is different to the "Standard" option
5. The "Download as JSON" link is missing

In `API Key modal > Custom Steps`:
1. I think the verb on the button should be `Generate` - ideally `Generate API key` rather than the current `Add API key`
2. I believe that while text in a modal should have a 20% margin on the right hand side, fields should be full-width.
3. The first field is called "Descriptive name" - I'd like this field to be identical to the one in the "Standard" option please.
4. There is a lot of empty space between the "Descriptive name" field and the Radio button selection - I'd expect this to be smaller?
5. While the key is generating, I think the loading text with the spinner should just say "Generating..."
6. Once the key is generated, I think the primary button text needs to be "Copy & close" per some complaints about its' current text in [Slack](https://ibmapim.slack.com/archives/C0M053VPT/p1599658565344400?thread_ts=1599589238.319800&cid=C0M053VPT)
7. The field which displays the generated API key is not the same as the password-styled field in the "Standard" option
8. The font size and styling of the "This is your unique API key and is non-recoverable" text is different to the "Standard" option
9. The "Download as JSON" link is missing

**Comment by davidmenendez** [comment]
@chloepoulterdesign updates have been made based on your feedback https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-apikeymodal--standard

**Comment by chloepoulterdesign** [comment]
Wow David - you've done so much work on this. Thank you so so much.

I'm reallly sorry to have a couple of little things left:
### On 'Standard':
1. ![image](https://user-images.githubusercontent.com/47979346/104617623-924a9d00-5683-11eb-88f3-85ed6b628043.png)
The helper text is a bit close to the field. You can see the Carbon example has a bit more space:
![image](https://user-images.githubusercontent.com/47979346/104617842-d9d12900-5683-11eb-8296-feb2ecb90ad4.png)

2. Keyboard navigation - when I used the keyboard to open the modal, the focus did not move into the modal. When I hit `return` to trigger the modal and the modal opens, I would expect the active state to be applied to the field in the modal, so that I can start typing. 

### In `Minimal`:
1. Could we possibly use the carbon "inline loading" component for the "Generating..." state? 
![image](https://user-images.githubusercontent.com/47979346/104620696-3124c880-5687-11eb-9d9c-0a70eafb9c4a.png)
so that it would look like [this](https://www.carbondesignsystem.com/components/inline-loading/usage):
![image](https://user-images.githubusercontent.com/47979346/104620929-73e6a080-5687-11eb-886c-1fdec86ca99e.png)
2. There is also the same issue with padding as there was in `Standard` 

### In `Custom steps`:
1. I know that the content in this modal is kind of "placeholder" content - we expect teams to replace it with their own. However, if we can tweak it, it would be great.
It currently looks like this:
![image](https://user-images.githubusercontent.com/47979346/104621330-e192cc80-5687-11eb-99cf-475b08eb1da2.png)
I would expect the spacing between the field and Radio buttons to look like this:
![image](https://user-images.githubusercontent.com/47979346/104622724-88c43380-5689-11eb-9a58-27b56b66922b.png)
2. It would be great, when opening a modal, if we could make the first field/input in the modal "active" - for keyboard users, this means that they can just start typing when the modal opens. 
3. It may be that it doesn't make sense to do so in the storybook - but I would expect that "next" would be disabled until i complete the Application name and radio buttons.
4. When I hit "generate API", like in the "standard" example I would expect the fields to be disabled when the loading state appears.

**Comment by davidmenendez** [comment]
@chloepoulterdesign i'll get a pull request up shortly to address this round of feedback with the exception of the keyboard controls. I haven't done any work with keyboard controls and carbon components before, so I'll have to take some time to find out how to accomplish the keyboard control feedback you've provided.

**Comment by chloepoulterdesign** [comment]
Thank you!
There is more designer guidance on keybaoard interactions on the [carbon website](https://www.carbondesignsystem.com/components/modal/usage#focus). I'm not sure about resources specifically for developers, but the [accessibility site ](https://www.ibm.com/able/)is also very good.

**Comment by davidmenendez** [comment]
@chloepoulterdesign updates made based on your feedback with the exception of the keyboard accessibility things. Could you take a look? https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-apikeymodal--standard

**Comment by chloepoulterdesign** [comment]
@davidmenendez the keyboard interaction work you've done is a huge improvement - i think it cut my button presses in half!

Tiny bugs:
### In "standard"
1. the "eye" icon in the password field looks a couple of pixels too low 
![image](https://user-images.githubusercontent.com/47979346/106016056-fd01cc80-60b6-11eb-811d-f4fe9436947d.png)
2. When I hit "generate" the "generate" button remains enabled, rather than disabled. Once "generating" appears, I'd expect it to be disabled.
![image](https://user-images.githubusercontent.com/47979346/106016183-1acf3180-60b7-11eb-950e-e6109e07fa3f.png)

### In "Custom steps" 
I think you may have mentioned that there are issues with this one in your PR - but I'll put the issues I see here in case they are different!
1. When the user hits `Next` and comes to the second step, focus is not "in the modal" - i have to press `tab` twice before I see the "focus" area. When I do see it, focus is applied to the "x" in the top-right of the modal, rather than on the toggle that I need to interact with first.
2. When I hit "generate", there is the same issue as "standard" - the "generate" button remains enabled, rather than disabled. Once "generating" appears, I'd expect it to be disabled.
![image](https://user-images.githubusercontent.com/47979346/106016183-1acf3180-60b7-11eb-950e-e6109e07fa3f.png)
3. Again, the same as "standard", the "eye" icon in the password field looks a couple of pixels too low 
![image](https://user-images.githubusercontent.com/47979346/106016056-fd01cc80-60b6-11eb-811d-f4fe9436947d.png)

**Comment by davidmenendez** [comment]
@chloepoulterdesign last round of design feedback has been merged https://ibm-cloud-cognitive.netlify.app/?path=/story/experimental-apikeymodal--standard

**Comment by chloepoulterdesign** [comment]
I think it looks great @davidmenendez - bar the carbon issues we've identified about keyboard interactions in some of the modals, they look & work as expected. 
Design approved

**Comment by andrea-gm** [comment]
@davidmenendez can we close this issue and open a new one for the above mentioned carbon issues? or does it make more sense to keep this one open, add the "blocked" label, and move it back to "To do" ?

**Comment by lee-chase** [comment]
@andrea-gm please do not close any issues that are being tracked by the project board until we have an alternative way to indicate/record state. At the very least an issue is required to promote to released, with both checklist and process in place.

**Comment by andrea-gm** [comment]
@lee-chase makes sense! thank you. so the second option in my question then? :D

**Comment by lee-chase** [comment]
> @lee-chase makes sense! thank you. so the second option in my question then? :D 

Yes
