### ISSUE TITLE
Additional tag features: Design review

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/ibm-cloud-cognitive#687]
## What will this achieve?

Improved interaction and visuals

## How will success be measured?

Design review

## Additional information

1. This component should be available as "Additional tag features" under "Canary" or "Released" rather than "Internal"
2. The tooltip should appear on hover
3. Should the focus immediately go to the "View all tags" link? It looks a bit jarring. And it may not make sense to do so on hover. If the user is navigating with keyboard, similarly I would expect the focus to remain on the element they are on, which is the tag with "+12" and let them tab into the tooltip link when/if they want to.
4. The modal design doesn't match what is seen on the website (and probably a good thing...) Worth a check in with the designer, Courtney Banning, to ensure alignment between the component and published guideline.
5. In the storybook modal, the elements should span 100% of the width, not 80%, which is the guideline only for text within a modal. Components should span full width.

https://pages.github.ibm.com/cdai-design/pal/components/additional-tag-features/#behavior

**Comment by lee-chase** [comment]
So just to sum up:
- It is the design in question
- AdditionalTagFeatures is a rubbish name hence TagSet
- This was what was implemented https://ibm.invisionapp.com/share/ANO0H9RHEGK#/screens/319719111
- I forgot about the epic, hence internal
- Note in the epic the reasons for the current interactions. T
- The issues I raised discussed by design here https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/92 but not reported back to the epic.

I still maintain that
- The tooltip like popup if ugly and relies on Tags being text only. They are only by convention.
- The modal, when viewing all, looks worse if not showing as tags or having a filter. It also assumes tags are text.

With regards to the design review
1. AdditionalTagFeatures manages to be verbose without providing any useful information as to what the component is. This is why TagSet was used, we could use TagGroup, TagList.
2.  Hover is a poor interaction that does not work well for interactive elements such as this one. Carbon defines the clickable interactive tooltip for this scenario. Hover does not transfer focus to the item being hovered over and keyboard interactions will not transfer into the tooltip.
3. See 2. Plus, this is possible but not Carbon for an interactive tootlip.
4. Already discussed see epic, invision and issue.
5. Can you clarify, not sure I understand the point you are making.

**Comment by lee-chase** [comment]
@courtney-banning has given her approval of the implementation with PR #774

Note: Courtney has asked for the above github handle to be used.
