### ISSUE TITLE
Do we need to support Server Side Rendering from v1

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#72]
During the kick-off meeting (Monday August 10th) Dejan Glozic mentioned server-side rendering. 

Is this a requirement? If so how do we protect against introducing code that is not compatible with SSR.

**Comment by SimonFinney** [comment]
Somewhat relevant, but we have a crude test that allows us to check to see if a library can be imported in Node.js directly - https://github.com/carbon-design-system/ibm-security/blob/dev/scripts/ssr/index.js

**Comment by dglozic** [comment]
Server-side rendering is not something you do in a React component, with a single exception: you are not allowed to make references to DOM global objects outside of client-side-only lifecycle methods (presuming here we are using classes and not hooks but I am sure there is a hook equivalent).

We are currently using Carbon X components with server side rendering without issue because they are cleanly written with SSR in mind. We should just make sure we do the same :-).
