### ISSUE TITLE
Export release review

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-cloud-cognitive#777]
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [x] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [x] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [ ] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [x] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [x] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by sydrosa** [comment]
Some updates that'll need to be addressed before release:

- [ ] At least one design scenario needs to be updated so that the modal is _not_ opened. This allows for better documentation view (since right now, as soon as you open the documentation, you immediately see the modal)
- [ ] `preventCloseOnClickOutside` should be baked into the component, and not a prop for the user to change
- [ ] the 'x' should be removed -- the user must take an action here whether it be to export it or cancel it.
- [ ] all significant DOM elements should have meaningful classNames -- I'd add one to the header, body and footer of your modal
- [ ] The modal header should always have a 20% padding right -- see `CreateModal` for deets
- [ ] The modal description should always have a 20% padding right (yours has a padding right ON TOP of the 1rem padding for the modal body -- you might need to use `calc()` here to get the correct spacing 
- [ ] We want to use as little default props as possible, forcing the dev to input the correct props if they're required. Is it necessary to set a default for open? If all of them point to false, is it necessary to include them at all?
- [ ] `primaryButtonText` and `secondaryButtonText` should be required
- [ ] Replace `fireEvent` -- try `userEvent`

Once these are completed, lets go ahead and prepare the component for release:

- [ ]  the flags for the components in `package-settings.js` should be changed to true
- [ ]  the component SCSS should be included in `/src/components/_index-released-only.scss.`
- [ ]  run the tests, recreating snapshots (using `yarn jest -u`), and check in the updated public CSS snapshot as part of the PR
