### ISSUE TITLE
Toolbar — orientation

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#806]
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-orientation_attribute

**Comment by JaredDevine** [comment]
The challenges with this item have been outlined in #811. The additional challenge with this will be the orientation styling for the toolbar when it snaps into a vertical menu position rather than horizontal, everything will need to shift including the way the dropdown menus behave with a horizontal item list rather than a standard vertical version.

**Comment by SimonFinney** [comment]
I'm renaming this issue to focus solely on orientation as other behavior appears to be covered by #811, #812, and #813
