### ISSUE TITLE
Side Panel: Release review notes

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#849]
### Release review findings:

- [x] Complete a design review with Kacie
- [x] Let's rename `pageContentSelector` to `selectorPageContent` (breaking change for `CreateSidePanel` -- please deprecate if we _do_ have existing users
- [x] Open up a separate enhancement issue for mobile-friendliness
- [x] Back button for multi-step side panel should have the entire div become a button as opposed to just the surrounding area -- reach out with any questions
- [x] add aria-label to `back` button in multi-step panel
- [x] Add actions to the multi-step panel story template for consistency (and to remove the console error)
- [x] update _index-scss, constants.js, index.js,  copywrite to `2020, 2021` 
- [x] update collapsable heading to an h2 as opposed to the current h5
- [x] add expected behavior to test on line 185: `should test overlay exit animation`
- [x] Update codesandbox with component changes

Once one or more components have been reviewed for readiness, the following steps are needed:

- [x] the flags for the components in package-settings.js should be changed to true.
- [x] the component SCSS should be included in /src/components/_index-released-only.scss.
- [x] run the tests, recreating snapshots (using -u), and check in the updated public CSS snapshot. NB it is sufficient to run yarn jest styles -u to complete the snapshot updates.

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-cloud-cognitive/pull/851

**Comment by matthewgallo** [comment]
All items from review have been addressed, waiting for design approval

**Comment by matthewgallo** [comment]
## Design review guidelines

### Standards

- [ ] All pattern updates/changes/iterations have been discussed with the component developer
- [ ] Patterns have been approved by either DSAG or another approving entity

### Pattern and behavior

- [ ] The component behaves according to the guidelines set by the pattern maintainer
- [ ] The component’s UI matches the pattern specifications set by the pattern maintainer
- [ ] The component’s motion matches the specifications set by the pattern maintainer(s)
- [ ] The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [ ] Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile views

### Storybook

- [ ] A functioning component renders in Storybook
- [ ] The Storybook displays multiple scenarios that show how the component can be used
- [ ] Changing props in the Storybook updates the component

**Comment by kacierae10** [comment]
### Design review guidelines
**Standards**

- [ ]  All pattern updates/changes/iterations have been discussed with the component developer
- [X]  Patterns have been approved by either DSAG or another approving entity

 
**Pattern and behavior**

- [X]  The component behaves according to the guidelines set by the pattern maintainer
- [ ]  The component’s UI matches the pattern specifications set by the pattern maintainer
- [X]  The component’s motion matches the specifications set by the pattern maintainer(s)
- [ ]  The UI produced is responsive, cross-browser, and responds to the currently set Carbon theme.
- [X]  Colors, themes, sizes and additional props are true and correct, aligning with Carbon set tokens (unless otherwise specified by the pattern)
- [ ] Paddings/margins/spacings are true and correct, in both desktop and mobile views

**Storybook**

- [X]  A functioning component renders in Storybook
- [X]  The Storybook displays multiple scenarios that show how the component can be used
- [X]  Changing props in the Storybook updates the component

----
Updates

- [ ] Need `$spacing-03` for Top and left padding on back navigation button
![Screen Shot 2021-06-16 at 6 50 21 AM](https://user-images.githubusercontent.com/25442116/122214194-6f5d2880-ce6f-11eb-9ec3-2413df7d11fd.png)

- [ ] For static title, when the user scrolls to the bottom the description text begins to scroll up--Should it stay in view?
![Screen Shot 2021-06-16 at 6 58 09 AM](https://user-images.githubusercontent.com/25442116/122215015-5dc85080-ce70-11eb-900f-ab17089b9695.png)

- [ ] Unsure how to test mobile views, but we don't have any guidance in the component for mobile, so unsure if this is required for the release


---
*FYI* @matthewgallo

**Comment by matthewgallo** [comment]
Thanks @kacierae10, I'll take a look!

**Comment by matthewgallo** [comment]
Hey @kacierae10, we have an issue open to make any mobile changes needed for this component (as an enhancement). the other two items you brought up have been addressed.

**Comment by kacierae10** [comment]
Looks good!

**Comment by matthewgallo** [comment]
Complete, component is released.
