### ISSUE TITLE
Import Modal: Release review notes

### ISSUE THREAD

**Issue by sydrosa** [carbon-design-system/ibm-cloud-cognitive#863]
Findings from release review:

- [x] Rename the prop `body` to `description` in `ImportModal.js`
- [x] To maintain consistency with Carbon, let's go ahead and rename the prop `validFileTypes` to `accept` (we think your prop name is better). You can see Carbon's prop names [here](https://react.carbondesignsystem.com/?path=/docs/components-fileuploader--drag-and-drop-upload-container-example-application)
- [x] The 'x' on the modal should be removed, and the prop associated with the `iconDescription` for the 'x' can also be removed
- [x] You'll need to update your `ImportModal.mdx` file so that the code preview shows
- [x] in line 108, you create a file object with key of 'status' and a value of 'pending' -- where does this show in the UI and is there anyway to test this? How can we/a user see if a file is "pending"?
- [x] On line 199, you're using an inline style of `width: 100%` to override the Carbon styles -- let's add an additional className like `${blockClass}__foo-bar ${pkg.carbon-prefix}--file-container` and add the styles to that? (I'm not sure if pkg.carbon-prefix is the correct way to get the prefix -- will find out for you. We definitely shouldn't be using `bx` though since I believe this is being changed in Carbon 11)
- [x] In line 178, remove the `div` tag and replace with a `<p>` tag -- this will remove the need to target a `p` tag in line 39,40 of your SCSS file. Same for 169
- [x] The title, file drop header, and any other text inside of this modal should also have a `padding-right` of `20% - $spacing-05` to match the description text. 
- [x] You've included some functionality for the ability to upload/import more than one file (which could happen in the future) however, the way you're updating state for files would reset if a user uploaded files from their computer _and_ from a URL. Something to think about. (`updateFiles` function and `fetchFile` function)
- [x] On line 124 of the `.test.js` file, you have expected functionality that the `fileUploadLabel` text will be visible to the user, however, if the user passes in a function that causes the modal to close, this test would no longer be true. Perhaps you can move this up in the test _before_ the `onRequestSubmit` function is triggered
- [x] In your .test.js file, if you were to remove the two optional props for `fetchErrorBody` and `fetchErrorHeader`, you'd have two tests fail. Seems to me that it might make sense to change those tests to test against the required props `defaultErrorBody` and `defaultErrorHeader` _instead_ or to have some sort of conditional that checks for `fetchError` _or_ `defaultError`
- [x] Needs a code sandbox

**Comment by davidmenendez** [comment]
> body to description

just out of curiosity why this decision? every other modal i've made uses `body` for the body content

> line 108

that file status is used for `FileUploaderItem` (line 204) which shows different icons based on the status on the upload.

> line 199

there was an issue where there was an underlying component in file uploader that was being affected by `bx--file-container` but i should be able to fix that.

> line 178 & 169 remove div tags

the reason for that is that carbon overwrites that `.bx--modal-content > p` that's why i just wrapped the p tags in divs, but if it's preferable i can update the html and css to be more specific. probably `.#{$block-class}__body-container .#{$block-class}__label`

> functionality for the ability to upload/import more than one file 

initially i coded this to support multiple file uploads, but i was later informed that import only supports a single upload. personally i don't think we should code around something that may or may not ever exist as a feature though. the current implementation is great for our single file usecase in my opinion.

thanks for the feedback. i'll work through this today

**Comment by matthewgallo** [comment]
If all the other modals use `body`, lets keep it the same then. We thought `description` made more sense because it looks as though the `body` prop is used to display the text below the title (description text).

**Comment by sydrosa** [comment]
> If all the other modals use `body`, lets keep it the same then. We thought `description` made more sense because it looks as though the `body` prop is used to display the text below the title (description text).

Actually, only _some_ of the modals use `body`. Others use `description`. We should probably talk it over in the channel to be on the same page.
