### ISSUE TITLE
Why are security components not relocating code to here

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#87]
The security components added so far are simply wrappers around components found in https://github.com/carbon-design-system/ibm-security why is component code not being located in this repository?

**Comment by SimonFinney** [comment]
Once this package is published and consumable, our current thinking is to migrate the source code for Security components available in this repo's Storybook over to this repo, and reverse the referencing so that `@carbon/ibm-security` will depend on `@carbon/ibm-cloud-paks` - This way we can cause minimal disruption to teams currently building on Cloud Pak for Security.
