### ISSUE TITLE
ActionBar release review (internal, required for PageHeader release)

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-cloud-cognitive#939]
Component reviews for readiness
Reviews will be carried out by one or more members of the core contribution team. They will include as a minimum the following checks, which establish the "definition of done" for a component.

Paste the following checklist into the epic or issue under which the component is being made ready, then check where criteria passed, and add notes to clarify how an item is complete or what remains to be done: for anything more than minor/simple items, open issues to track them.

Tip You should be able to copy and paste the section below directly into a GitHub comment, then check where criteria passed, strike out where not applicable, and add notes to each item where applicable.

Once one or more components have been reviewed for readiness, the following steps are needed:

the flags for the components in package-settings.js should be changed to true.
the component SCSS should be included in /src/components/_index-released-only.scss.
run the tests, recreating snapshots (using -u), and check in the updated public CSS snapshot. NB it is sufficient to run yarn jest styles -u to complete the snapshot updates.
### Readiness

- [x] One or more scenarios for a design pattern have been identified as a useful unit of functionality to publish.
- [x] A functioning component or components delivering those scenarios have been delivered and merged to master.
- [x] Design maintainer has approved the implementation for those scenarios (via a comment on the relevant issue/epic).

### Engineering review

- [x] Breaking changes have only been introduced with prior approval, discussion and documented in release notes. Ideally deprecation notices in the prior major version must have been added in a timely fashion.
- [x] The implementation takes into account, and does not impair, remaining and anticipated design scenarios.
- [x] Public component features (names, props, etc) are consistent with Carbon-defined conventions and are consistent internally. Where there isn't an existing convention to apply, ensure robust precedents are being established.
- [x] The UI produced is accessible, responsive, translatable, cross-browser, and responds to the currently set Carbon theme.
- [x] Components are functional components using hooks.
- [x] Public components which produce DOM structures support className.
- [x] Public components support a ref (via React.forwardRef).
- [x] All significant DOM elements have meaningful classes.
- [x] Additional attributes that are not identified as props (such as title, aria-*, etc) are passed through to an appropriate DOM node of the component as HTML attributes.
- [x] No warnings, errors or log messages in the console.
- [x] Each public component JS is exported in /src/components/index.js, each public component SCSS is included in /src/components/_index.scss, and each public component has a flag in package-settings.js.

### Standards

- [x] No linter warnings or errors are produced.
- [x] Carbon tokens (theme, layout, motion) are used unless the design specifies otherwise.
- [x] Code is formatted according to prettier rules (no use of //prettier-ignore).
- [x] Code is clear, maintainable and follows standard React practices and the code guidelines.
- [x] Copyright header in every source file (js, css, scss etc.) with the appropriate years.

### Testing

- [x] There is a set of test cases for the components.
- [x] The tests exercise all inputs (props, slots, etc) and verify appropriate outputs.
- [x] The tests validate the behaviors and interactions defined in the design where practical.
- [x] The tests achieve 100% coverage. Usage of istanbul ignore is appropriate and not extensive.
- [x] No warnings, errors or log messages in the test output.

### Documentation

- [x] Source code is satisfactorily commented and provides DocGen comments for all public components and their props.
- [x] There is a story for each design scenario. The stories expose all relevant props and actions, and additional usage documentation and code samples are available on the 'Docs' tab along with the props table.
- [ ] There is a sandbox (or multiple sandboxes if appropriate) on CodeSandbox for the components.

**Comment by davidmenendez** [comment]
Here are some initial thoughts and comments on the code

- you're defining a separate sub component within `ActionBar.js` (`ActionBarOverflowItems`) and to be honest I think that it should be separated into it's own file. i don't see the benefit of containing `ActionBarOverflowItems` within `ActionBar`, so if only to simplify `ActionBar.js` i think `ActionBarOverflowItems` needs to be moved into it's own file.
- in regards to `ActionBarOverflowItems` I'm seeing the class name `${blockClass}__overflow-menu` used numerous times. if another block class type variable were created to use that value we could cut down on code by referring to `blockClass2` or something instead of repeating `${blockClass}__overflow-menu-*` numerous times. this of course can easily be alleviated by using my previous suggestion of moving it to it's own file.
- on line 69 we have `overflowItems.map((item, index)` according to react this is an anti pattern.. We should instead ask the user to provide their own id's. "We don’t recommend using indexes for keys if the order of items may change. This can negatively impact performance and may cause issues with component state. When you don’t have stable IDs for rendered items, you may use the item index as a key as a last resort."
- same issue on line 114
- on line 205 we have `...prepareProps(Button.propTypes, [` as annoying as this is I think for the sake of fully using storybook as documentation we can't do this. it's very annoying that storybook doesn't currently have a way to extract the prop details to display when you try to cheat by doing something like using the proptypes from another component. believe me I wish we could just do that, but since we need to rely on having good documentation for consumers and developers I don't think we can use this pattern and instead have to just type everything out. i'm not saying the documentation needs to be extremely explicit even it just needs to be able to display all the props.
- same comment as above regarding `ActionBarItem.js` on line 73

just for the sake of record keeping- can you point to where the designer has signed off on the design implementation?

**Comment by davidmenendez** [comment]
@lee-chase still going through with a fine tooth comb, but i've mentioned some initial comments and thoughts.

**Comment by lee-chase** [comment]
For the record https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/59#issuecomment-861013992
and https://github.com/carbon-design-system/ibm-cloud-cognitive/issues/897#issuecomment-861013562

**Comment by lee-chase** [comment]
@davidmenendez points addressed in #967 

With regards to your points on PropTypes. I have added some additional commentary to ActionBar.js but persist with using Button.propTypes. This is because we specifically want to only highlight the props important to ActionBarItem, but support most Button props. This has previously been discussed at scrum and we felt that declaring all 24 Button propTypes would not be helpful to our end users obscuring the main usecase.

We can discuss again at scrum if you feel this interpretation of our discussion is incorrect.

**Comment by davidmenendez** [comment]
@lee-chase went back over the code and everything looks good to me. i think all that's left is to add a sandbox

**Comment by lee-chase** [comment]
No code sandbox @davidmenendez this is an internal part of the page header.
